/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package horario;
import Controlador.controller;
import paneles.*;
import paneles.CambiaPanel;
import paneles.pnlIni;

/**
 *
 * @author meggu
 */
public class MainMenu extends javax.swing.JFrame {
     controller control;
    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
        this.setLocationRelativeTo(this);
        this.btnRSIni.setSelected(true);
        
        new CambiaPanel(pnlPrincipal, new pnlIni());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pnlBase = new javax.swing.JPanel();
        pnlBorde = new javax.swing.JPanel();
        btnRSMenu = new rsbuttom.RSButtonMetro();
        pnlSideBar = new javax.swing.JPanel();
        btnRSIni = new rsbuttom.RSButtonMetro();
        btnRSHora = new rsbuttom.RSButtonMetro();
        btnRSEdi = new rsbuttom.RSButtonMetro();
        btnRSEEX1 = new rsbuttom.RSButtonMetro();
        pnlPrincipal = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlBase.setBackground(new java.awt.Color(102, 102, 102));
        pnlBase.setForeground(new java.awt.Color(102, 102, 102));
        pnlBase.setPreferredSize(new java.awt.Dimension(1225, 999));
        pnlBase.setLayout(new java.awt.GridBagLayout());

        pnlBorde.setBackground(new java.awt.Color(0, 102, 51));
        pnlBorde.setForeground(new java.awt.Color(0, 102, 51));

        btnRSMenu.setBackground(new java.awt.Color(0, 102, 51));
        btnRSMenu.setForeground(new java.awt.Color(0, 102, 51));
        btnRSMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/menu.png"))); // NOI18N
        btnRSMenu.setColorHover(new java.awt.Color(0, 153, 51));
        btnRSMenu.setColorNormal(new java.awt.Color(0, 102, 51));
        btnRSMenu.setColorPressed(new java.awt.Color(0, 153, 51));
        btnRSMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRSMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBordeLayout = new javax.swing.GroupLayout(pnlBorde);
        pnlBorde.setLayout(pnlBordeLayout);
        pnlBordeLayout.setHorizontalGroup(
            pnlBordeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBordeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnRSMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1162, Short.MAX_VALUE))
        );
        pnlBordeLayout.setVerticalGroup(
            pnlBordeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBordeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnRSMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                .addContainerGap())
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 1028;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.3;
        gridBagConstraints.weighty = 1.3;
        pnlBase.add(pnlBorde, gridBagConstraints);

        pnlSideBar.setBackground(new java.awt.Color(153, 153, 153));
        pnlSideBar.setForeground(new java.awt.Color(255, 255, 255));
        pnlSideBar.setPreferredSize(new java.awt.Dimension(182, 800));

        btnRSIni.setBackground(new java.awt.Color(204, 204, 204));
        btnRSIni.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/home.png"))); // NOI18N
        btnRSIni.setText("      INICIO");
        btnRSIni.setColorHover(new java.awt.Color(204, 204, 255));
        btnRSIni.setColorNormal(new java.awt.Color(204, 204, 204));
        btnRSIni.setColorPressed(new java.awt.Color(204, 204, 255));
        btnRSIni.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnRSIni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRSIniActionPerformed(evt);
            }
        });

        btnRSHora.setBackground(new java.awt.Color(204, 204, 204));
        btnRSHora.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/collection.png"))); // NOI18N
        btnRSHora.setText(" HORARIO");
        btnRSHora.setColorHover(new java.awt.Color(204, 204, 255));
        btnRSHora.setColorNormal(new java.awt.Color(204, 204, 204));
        btnRSHora.setColorPressed(new java.awt.Color(204, 204, 255));
        btnRSHora.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnRSHora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRSHoraActionPerformed(evt);
            }
        });

        btnRSEdi.setBackground(new java.awt.Color(204, 204, 204));
        btnRSEdi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/web.png"))); // NOI18N
        btnRSEdi.setText("     EDITAR");
        btnRSEdi.setColorHover(new java.awt.Color(204, 204, 255));
        btnRSEdi.setColorNormal(new java.awt.Color(204, 204, 204));
        btnRSEdi.setColorPressed(new java.awt.Color(204, 204, 255));
        btnRSEdi.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnRSEdi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRSEdiActionPerformed(evt);
            }
        });

        btnRSEEX1.setBackground(new java.awt.Color(204, 204, 204));
        btnRSEEX1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ios.png"))); // NOI18N
        btnRSEEX1.setText("       EXTRA");
        btnRSEEX1.setColorHover(new java.awt.Color(204, 204, 255));
        btnRSEEX1.setColorNormal(new java.awt.Color(204, 204, 204));
        btnRSEEX1.setColorPressed(new java.awt.Color(204, 204, 255));
        btnRSEEX1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnRSEEX1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRSEEX1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlSideBarLayout = new javax.swing.GroupLayout(pnlSideBar);
        pnlSideBar.setLayout(pnlSideBarLayout);
        pnlSideBarLayout.setHorizontalGroup(
            pnlSideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnRSIni, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnRSHora, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
            .addComponent(btnRSEdi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnRSEEX1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlSideBarLayout.setVerticalGroup(
            pnlSideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSideBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnRSIni, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRSHora, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRSEdi, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRSEEX1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(733, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 41;
        gridBagConstraints.ipady = 727;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weighty = 1.4;
        gridBagConstraints.insets = new java.awt.Insets(1, 0, 8, 0);
        pnlBase.add(pnlSideBar, gridBagConstraints);

        pnlPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        pnlPrincipal.setLayout(new javax.swing.BoxLayout(pnlPrincipal, javax.swing.BoxLayout.LINE_AXIS));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 800;
        gridBagConstraints.ipady = 700;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 8, 0);
        pnlBase.add(pnlPrincipal, gridBagConstraints);
        pnlPrincipal.getAccessibleContext().setAccessibleName("");
        pnlPrincipal.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBase, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRSIniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRSIniActionPerformed
        // TODO add your handling code here:
        new CambiaPanel(pnlPrincipal, new pnlIni());
    }//GEN-LAST:event_btnRSIniActionPerformed

    private void btnRSHoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRSHoraActionPerformed
        // TODO add your handling code here:
        new CambiaPanel(pnlPrincipal, new pnlHora());
    }//GEN-LAST:event_btnRSHoraActionPerformed

    private void btnRSEdiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRSEdiActionPerformed
        // TODO add your handling code here:
        new CambiaPanel(pnlPrincipal, new pnlEditar());
    }//GEN-LAST:event_btnRSEdiActionPerformed

    private void btnRSMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRSMenuActionPerformed
        // MOVIMIENTO DEL MENU SLIDE
        int posicion = this.pnlSideBar.getX();
        if (posicion > -1)   // si no esta seleccionado
            Animacion.Animacion.mover_izquierda(0, -182, 2, 2, pnlSideBar);
        else     //si se selecciona
            Animacion.Animacion.mover_derecha(-182, 0, 2, 2, pnlSideBar);
    }//GEN-LAST:event_btnRSMenuActionPerformed

    private void btnRSEEX1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRSEEX1ActionPerformed
        // TODO add your handling code here:
        new CambiaPanel(pnlPrincipal, new pnlExtra());
        
    }//GEN-LAST:event_btnRSEEX1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rsbuttom.RSButtonMetro btnRSEEX1;
    private rsbuttom.RSButtonMetro btnRSEdi;
    private rsbuttom.RSButtonMetro btnRSHora;
    private rsbuttom.RSButtonMetro btnRSIni;
    private rsbuttom.RSButtonMetro btnRSMenu;
    private javax.swing.JPanel pnlBase;
    private javax.swing.JPanel pnlBorde;
    private javax.swing.JPanel pnlPrincipal;
    private javax.swing.JPanel pnlSideBar;
    // End of variables declaration//GEN-END:variables
}
