/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paneles;

/**
 *
 * @author LAB_L11
 */
public class pnlEdit extends javax.swing.JPanel {

    /**
     * Creates new form pnlEdit
     */
    public pnlEdit() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBase = new javax.swing.JPanel();
        btnCargar = new rsbuttom.RSButtonMetro();
        btnCargar1 = new rsbuttom.RSButtonMetro();
        btnCargar2 = new rsbuttom.RSButtonMetro();
        btnCargar3 = new rsbuttom.RSButtonMetro();
        btnCargar4 = new rsbuttom.RSButtonMetro();
        btnCargar5 = new rsbuttom.RSButtonMetro();

        pnlBase.setBackground(new java.awt.Color(102, 102, 102));
        pnlBase.setForeground(new java.awt.Color(102, 102, 102));
        pnlBase.setPreferredSize(new java.awt.Dimension(1105, 962));

        btnCargar.setBackground(new java.awt.Color(204, 204, 204));
        btnCargar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/market.png"))); // NOI18N
        btnCargar.setText("     CARGAR MATERIAS");
        btnCargar.setColorHover(new java.awt.Color(204, 204, 255));
        btnCargar.setColorNormal(new java.awt.Color(204, 204, 204));
        btnCargar.setColorPressed(new java.awt.Color(204, 204, 255));
        btnCargar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarActionPerformed(evt);
            }
        });

        btnCargar1.setBackground(new java.awt.Color(204, 204, 204));
        btnCargar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/chat.png"))); // NOI18N
        btnCargar1.setText("     MODIFICAR ACTIVIDADES");
        btnCargar1.setColorHover(new java.awt.Color(204, 204, 255));
        btnCargar1.setColorNormal(new java.awt.Color(204, 204, 204));
        btnCargar1.setColorPressed(new java.awt.Color(204, 204, 255));
        btnCargar1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnCargar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargar1ActionPerformed(evt);
            }
        });

        btnCargar2.setBackground(new java.awt.Color(204, 204, 204));
        btnCargar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ios.png"))); // NOI18N
        btnCargar2.setText("     MODIFICAR MATERIAS");
        btnCargar2.setColorHover(new java.awt.Color(204, 204, 255));
        btnCargar2.setColorNormal(new java.awt.Color(204, 204, 204));
        btnCargar2.setColorPressed(new java.awt.Color(204, 204, 255));
        btnCargar2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnCargar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargar2ActionPerformed(evt);
            }
        });

        btnCargar3.setBackground(new java.awt.Color(204, 204, 204));
        btnCargar3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/android.png"))); // NOI18N
        btnCargar3.setText("     ELIMINAR MATERIAS");
        btnCargar3.setColorHover(new java.awt.Color(204, 204, 255));
        btnCargar3.setColorNormal(new java.awt.Color(204, 204, 204));
        btnCargar3.setColorPressed(new java.awt.Color(204, 204, 255));
        btnCargar3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnCargar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargar3ActionPerformed(evt);
            }
        });

        btnCargar4.setBackground(new java.awt.Color(204, 204, 204));
        btnCargar4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/feeedback.png"))); // NOI18N
        btnCargar4.setText("     ACTIVIDADES EXTRAS");
        btnCargar4.setColorHover(new java.awt.Color(204, 204, 255));
        btnCargar4.setColorNormal(new java.awt.Color(204, 204, 204));
        btnCargar4.setColorPressed(new java.awt.Color(204, 204, 255));
        btnCargar4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnCargar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargar4ActionPerformed(evt);
            }
        });

        btnCargar5.setBackground(new java.awt.Color(204, 204, 204));
        btnCargar5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/web.png"))); // NOI18N
        btnCargar5.setText("     ELIMINAR ACTIVIDADES");
        btnCargar5.setColorHover(new java.awt.Color(204, 204, 255));
        btnCargar5.setColorNormal(new java.awt.Color(204, 204, 204));
        btnCargar5.setColorPressed(new java.awt.Color(204, 204, 255));
        btnCargar5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnCargar5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargar5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBaseLayout = new javax.swing.GroupLayout(pnlBase);
        pnlBase.setLayout(pnlBaseLayout);
        pnlBaseLayout.setHorizontalGroup(
            pnlBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBaseLayout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addGroup(pnlBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBaseLayout.createSequentialGroup()
                        .addGroup(pnlBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnCargar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCargar2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE))
                        .addGap(123, 123, 123))
                    .addGroup(pnlBaseLayout.createSequentialGroup()
                        .addComponent(btnCargar3, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)))
                .addGroup(pnlBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCargar1, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCargar5, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(167, Short.MAX_VALUE))
            .addGroup(pnlBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBaseLayout.createSequentialGroup()
                    .addContainerGap(595, Short.MAX_VALUE)
                    .addComponent(btnCargar4, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(168, 168, 168)))
        );
        pnlBaseLayout.setVerticalGroup(
            pnlBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBaseLayout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addComponent(btnCargar, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(pnlBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCargar2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCargar1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(pnlBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCargar5, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCargar3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(476, Short.MAX_VALUE))
            .addGroup(pnlBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlBaseLayout.createSequentialGroup()
                    .addGap(156, 156, 156)
                    .addComponent(btnCargar4, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(723, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCargarActionPerformed

    private void btnCargar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCargar1ActionPerformed

    private void btnCargar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCargar2ActionPerformed

    private void btnCargar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargar3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCargar3ActionPerformed

    private void btnCargar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargar4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCargar4ActionPerformed

    private void btnCargar5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargar5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCargar5ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rsbuttom.RSButtonMetro btnCargar;
    private rsbuttom.RSButtonMetro btnCargar1;
    private rsbuttom.RSButtonMetro btnCargar2;
    private rsbuttom.RSButtonMetro btnCargar3;
    private rsbuttom.RSButtonMetro btnCargar4;
    private rsbuttom.RSButtonMetro btnCargar5;
    private javax.swing.JPanel pnlBase;
    // End of variables declaration//GEN-END:variables
}
