/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paneles;
import Controlador.controller;
import clases.Actividad;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import javax.swing.ButtonGroup;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.JTextField;
import rsbuttom.RSButtonMetro;
import manejoXML.*;
/**
 *
 * @author Diego
 */
public class pnlExtra extends javax.swing.JPanel {
     controller control;
      Actividad actividad = new Actividad();
     DefaultTableModel dtm2 = new DefaultTableModel();
     controlXMLAE XMLAE = new controlXMLAE();
    /**
     * Creates new form pnlExtra
     */
    public pnlExtra() {
        initComponents();
        control = new controller(cmbSlcnDiaE1,cmbSlcnDiaE2,cmbSlcnDiaE3,cmbSlcnDiaE4,cmbSlcnDiaE5,cmbSlcnHoraFiED1,cmbSlcnHoraFiED2,cmbSlcnHoraFiED3,cmbSlcnHoraFiED4,cmbSlcnHoraFiED5,cmbSlcnHoraInED1,cmbSlcnHoraInED2,cmbSlcnHoraInED3,cmbSlcnHoraInED4,cmbSlcnHoraInED5,txtAExtra,txtNroActividad,rdioDiaE1,rdioDiaE2,rdioDiaE3,rdioDiaE4,rdioDiaE5,rdioHoraE1D1,rdioHoraE1D2,rdioHoraE1D3,rdioHoraE1D4,rdioHoraE1D5,rdioHoraE2D1,rdioHoraE2D2,rdioHoraE2D3,rdioHoraE2D4,rdioHoraE2D5,rdioHoraE3D1,rdioHoraE3D2,rdioHoraE3D3,rdioHoraE3D4,rdioHoraE3D5,btnAgregarE,btnModificarE,btnEliminarE,btnAModificacionE);
        controlXMLAE datosXMLAE = new controlXMLAE();
        
        llenarTablaAE(datosXMLAE);
        rdioGroupDiaE.add(rdioDiaE1);
        rdioGroupDiaE.add(rdioDiaE2);
        rdioGroupDiaE.add(rdioDiaE3);
        rdioGroupDiaE.add(rdioDiaE4);
        rdioGroupDiaE.add(rdioDiaE5);
        
        rdioGroupDiaE1.add(rdioHoraE1D1);
        rdioGroupDiaE1.add(rdioHoraE2D1);
        rdioGroupDiaE1.add(rdioHoraE3D1);
        
        rdioGroupDiaE2.add(rdioHoraE1D2);
        rdioGroupDiaE2.add(rdioHoraE2D2);
        rdioGroupDiaE2.add(rdioHoraE3D2);
        
        rdioGroupDiaE3.add(rdioHoraE1D3);
        rdioGroupDiaE3.add(rdioHoraE2D3);
        rdioGroupDiaE3.add(rdioHoraE3D3);
        
        rdioGroupDiaE4.add(rdioHoraE1D4);
        rdioGroupDiaE4.add(rdioHoraE2D4);
        rdioGroupDiaE4.add(rdioHoraE3D4);
        
        rdioGroupDiaE5.add(rdioHoraE1D5);
        rdioGroupDiaE5.add(rdioHoraE2D5);
        rdioGroupDiaE5.add(rdioHoraE3D5);
        
       control.botonAM(btnAModificacionE); 
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rdioGroupDiaE1 = new javax.swing.ButtonGroup();
        rdioGroupDiaE2 = new javax.swing.ButtonGroup();
        rdioGroupDiaE3 = new javax.swing.ButtonGroup();
        rdioGroupDiaE4 = new javax.swing.ButtonGroup();
        rdioGroupDiaE5 = new javax.swing.ButtonGroup();
        rdioGroupDiaE = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txtAExtra = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        rdioDiaE1 = new javax.swing.JRadioButton();
        rdioDiaE2 = new javax.swing.JRadioButton();
        rdioDiaE3 = new javax.swing.JRadioButton();
        rdioDiaE4 = new javax.swing.JRadioButton();
        rdioDiaE5 = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        rdioHoraE1D1 = new javax.swing.JRadioButton();
        rdioHoraE2D1 = new javax.swing.JRadioButton();
        rdioHoraE3D1 = new javax.swing.JRadioButton();
        cmbSlcnDiaE1 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        cmbSlcnHoraInED1 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        cmbSlcnHoraFiED1 = new javax.swing.JComboBox<>();
        jPanel6 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        rdioHoraE1D2 = new javax.swing.JRadioButton();
        rdioHoraE2D2 = new javax.swing.JRadioButton();
        rdioHoraE3D2 = new javax.swing.JRadioButton();
        cmbSlcnDiaE2 = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        cmbSlcnHoraInED2 = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        cmbSlcnHoraFiED2 = new javax.swing.JComboBox<>();
        jPanel8 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        rdioHoraE1D3 = new javax.swing.JRadioButton();
        rdioHoraE2D3 = new javax.swing.JRadioButton();
        rdioHoraE3D3 = new javax.swing.JRadioButton();
        cmbSlcnDiaE3 = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        cmbSlcnHoraInED3 = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        cmbSlcnHoraFiED3 = new javax.swing.JComboBox<>();
        jPanel9 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        rdioHoraE1D4 = new javax.swing.JRadioButton();
        rdioHoraE2D4 = new javax.swing.JRadioButton();
        rdioHoraE3D4 = new javax.swing.JRadioButton();
        cmbSlcnDiaE4 = new javax.swing.JComboBox<>();
        jLabel23 = new javax.swing.JLabel();
        cmbSlcnHoraInED4 = new javax.swing.JComboBox<>();
        jLabel24 = new javax.swing.JLabel();
        cmbSlcnHoraFiED4 = new javax.swing.JComboBox<>();
        jPanel10 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        rdioHoraE1D5 = new javax.swing.JRadioButton();
        rdioHoraE2D5 = new javax.swing.JRadioButton();
        rdioHoraE3D5 = new javax.swing.JRadioButton();
        cmbSlcnDiaE5 = new javax.swing.JComboBox<>();
        jLabel26 = new javax.swing.JLabel();
        cmbSlcnHoraInED5 = new javax.swing.JComboBox<>();
        jLabel27 = new javax.swing.JLabel();
        cmbSlcnHoraFiED5 = new javax.swing.JComboBox<>();
        jLabel28 = new javax.swing.JLabel();
        txtNroActividad = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaAExtra = new javax.swing.JTable();
        btnModificarE = new rsbuttom.RSButtonMetro();
        btnEliminarE = new rsbuttom.RSButtonMetro();
        btnAgregarE = new rsbuttom.RSButtonMetro();
        btnAModificacionE = new rsbuttom.RSButtonMetro();

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setForeground(new java.awt.Color(102, 102, 102));
        jPanel1.setPreferredSize(new java.awt.Dimension(1225, 999));

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setForeground(new java.awt.Color(102, 102, 102));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Actividad Extracurricular");

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setForeground(new java.awt.Color(102, 102, 102));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Número de días:");

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Actividad Extracurricular");

        rdioDiaE1.setBackground(new java.awt.Color(102, 102, 102));
        rdioDiaE1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rdioDiaE1.setForeground(new java.awt.Color(255, 255, 255));
        rdioDiaE1.setText("Uno");
        rdioDiaE1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdioDiaE1ActionPerformed(evt);
            }
        });

        rdioDiaE2.setBackground(new java.awt.Color(102, 102, 102));
        rdioDiaE2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rdioDiaE2.setForeground(new java.awt.Color(255, 255, 255));
        rdioDiaE2.setText("Dos");
        rdioDiaE2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdioDiaE2ActionPerformed(evt);
            }
        });

        rdioDiaE3.setBackground(new java.awt.Color(102, 102, 102));
        rdioDiaE3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rdioDiaE3.setForeground(new java.awt.Color(255, 255, 255));
        rdioDiaE3.setText("Tres");
        rdioDiaE3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdioDiaE3ActionPerformed(evt);
            }
        });

        rdioDiaE4.setBackground(new java.awt.Color(102, 102, 102));
        rdioDiaE4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rdioDiaE4.setForeground(new java.awt.Color(255, 255, 255));
        rdioDiaE4.setText("Cuatro");
        rdioDiaE4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdioDiaE4ActionPerformed(evt);
            }
        });

        rdioDiaE5.setBackground(new java.awt.Color(102, 102, 102));
        rdioDiaE5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rdioDiaE5.setForeground(new java.awt.Color(255, 255, 255));
        rdioDiaE5.setText("Cinco");
        rdioDiaE5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdioDiaE5ActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(102, 102, 102));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Bloques de hora (Día 1):");

        rdioHoraE1D1.setBackground(new java.awt.Color(102, 102, 102));
        rdioHoraE1D1.setForeground(new java.awt.Color(255, 255, 255));
        rdioHoraE1D1.setText("Una hora");

        rdioHoraE2D1.setBackground(new java.awt.Color(102, 102, 102));
        rdioHoraE2D1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rdioHoraE2D1.setForeground(new java.awt.Color(255, 255, 255));
        rdioHoraE2D1.setText("Dos horas");

        rdioHoraE3D1.setBackground(new java.awt.Color(102, 102, 102));
        rdioHoraE3D1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rdioHoraE3D1.setForeground(new java.awt.Color(255, 255, 255));
        rdioHoraE3D1.setText("Tres horas");

        cmbSlcnDiaE1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lunes", "Martes", "Miércoles", "Jueves", "Viernes" }));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Hora inicial:");

        cmbSlcnHoraInED1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "7:00 A.M", "8:00 A.M", "9:00 A.M", "10:00 A.M", "11:00 A.M", "12:00 A.M", "1:00 P.M", "2:00 P.M", "3:00 P.M", "4:00 P.M", "5:00 P.M", "6:00 P.M", "7:00 P.M", "8:00 P.M" }));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Hora final:");

        cmbSlcnHoraFiED1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "7:00 A.M", "8:00 A.M", "9:00 A.M", "10:00 A.M", "11:00 A.M", "12:00 A.M", "1:00 P.M", "2:00 P.M", "3:00 P.M", "4:00 P.M", "5:00 P.M", "6:00 P.M", "7:00 P.M", "8:00 P.M" }));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(cmbSlcnHoraInED1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(cmbSlcnHoraFiED1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addGap(63, 63, 63))))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jLabel6))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(cmbSlcnDiaE1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(rdioHoraE1D1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rdioHoraE2D1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdioHoraE3D1)
                .addGap(37, 37, 37))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdioHoraE1D1)
                    .addComponent(rdioHoraE2D1)
                    .addComponent(rdioHoraE3D1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmbSlcnDiaE1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbSlcnHoraInED1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbSlcnHoraFiED1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(102, 102, 102));
        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Bloques de hora (Día 2):");

        rdioHoraE1D2.setBackground(new java.awt.Color(102, 102, 102));
        rdioHoraE1D2.setForeground(new java.awt.Color(255, 255, 255));
        rdioHoraE1D2.setText("Una hora");

        rdioHoraE2D2.setBackground(new java.awt.Color(102, 102, 102));
        rdioHoraE2D2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rdioHoraE2D2.setForeground(new java.awt.Color(255, 255, 255));
        rdioHoraE2D2.setText("Dos horas");

        rdioHoraE3D2.setBackground(new java.awt.Color(102, 102, 102));
        rdioHoraE3D2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rdioHoraE3D2.setForeground(new java.awt.Color(255, 255, 255));
        rdioHoraE3D2.setText("Tres horas");

        cmbSlcnDiaE2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lunes", "Martes", "Miércoles", "Jueves", "Viernes" }));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Hora inicial:");

        cmbSlcnHoraInED2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "7:00 A.M", "8:00 A.M", "9:00 A.M", "10:00 A.M", "11:00 A.M", "12:00 A.M", "1:00 P.M", "2:00 P.M", "3:00 P.M", "4:00 P.M", "5:00 P.M", "6:00 P.M", "7:00 P.M", "8:00 P.M" }));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Hora final:");

        cmbSlcnHoraFiED2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "7:00 A.M", "8:00 A.M", "9:00 A.M", "10:00 A.M", "11:00 A.M", "12:00 A.M", "1:00 P.M", "2:00 P.M", "3:00 P.M", "4:00 P.M", "5:00 P.M", "6:00 P.M", "7:00 P.M", "8:00 P.M" }));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(rdioHoraE1D2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rdioHoraE2D2)
                        .addGap(16, 16, 16)
                        .addComponent(rdioHoraE3D2)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(cmbSlcnHoraInED2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmbSlcnHoraFiED2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel14)
                        .addGap(57, 57, 57))))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jLabel12))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(cmbSlcnDiaE2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdioHoraE1D2)
                    .addComponent(rdioHoraE2D2)
                    .addComponent(rdioHoraE3D2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmbSlcnDiaE2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbSlcnHoraInED2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbSlcnHoraFiED2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel8.setBackground(new java.awt.Color(102, 102, 102));
        jPanel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Bloques de hora (Día 3):");

        rdioHoraE1D3.setBackground(new java.awt.Color(102, 102, 102));
        rdioHoraE1D3.setForeground(new java.awt.Color(255, 255, 255));
        rdioHoraE1D3.setText("Una hora");

        rdioHoraE2D3.setBackground(new java.awt.Color(102, 102, 102));
        rdioHoraE2D3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rdioHoraE2D3.setForeground(new java.awt.Color(255, 255, 255));
        rdioHoraE2D3.setText("Dos horas");

        rdioHoraE3D3.setBackground(new java.awt.Color(102, 102, 102));
        rdioHoraE3D3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rdioHoraE3D3.setForeground(new java.awt.Color(255, 255, 255));
        rdioHoraE3D3.setText("Tres horas");

        cmbSlcnDiaE3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lunes", "Martes", "Miércoles", "Jueves", "Viernes" }));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Hora inicial:");

        cmbSlcnHoraInED3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "7:00 A.M", "8:00 A.M", "9:00 A.M", "10:00 A.M", "11:00 A.M", "12:00 A.M", "1:00 P.M", "2:00 P.M", "3:00 P.M", "4:00 P.M", "5:00 P.M", "6:00 P.M", "7:00 P.M", "8:00 P.M" }));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Hora final:");

        cmbSlcnHoraFiED3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "7:00 A.M", "8:00 A.M", "9:00 A.M", "10:00 A.M", "11:00 A.M", "12:00 A.M", "1:00 P.M", "2:00 P.M", "3:00 P.M", "4:00 P.M", "5:00 P.M", "6:00 P.M", "7:00 P.M", "8:00 P.M" }));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel8Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(cmbSlcnHoraInED3, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(cmbSlcnHoraFiED3, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel8Layout.createSequentialGroup()
                        .addComponent(rdioHoraE1D3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbSlcnDiaE3, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(rdioHoraE2D3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rdioHoraE3D3)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(jLabel18)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel20)
                .addGap(33, 33, 33))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdioHoraE1D3)
                    .addComponent(rdioHoraE2D3)
                    .addComponent(rdioHoraE3D3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmbSlcnDiaE3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbSlcnHoraInED3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbSlcnHoraFiED3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel9.setBackground(new java.awt.Color(102, 102, 102));
        jPanel9.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Bloques de hora (Día 4):");

        rdioHoraE1D4.setBackground(new java.awt.Color(102, 102, 102));
        rdioHoraE1D4.setForeground(new java.awt.Color(255, 255, 255));
        rdioHoraE1D4.setText("Una hora");

        rdioHoraE2D4.setBackground(new java.awt.Color(102, 102, 102));
        rdioHoraE2D4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rdioHoraE2D4.setForeground(new java.awt.Color(255, 255, 255));
        rdioHoraE2D4.setText("Dos horas");

        rdioHoraE3D4.setBackground(new java.awt.Color(102, 102, 102));
        rdioHoraE3D4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rdioHoraE3D4.setForeground(new java.awt.Color(255, 255, 255));
        rdioHoraE3D4.setText("Tres horas");

        cmbSlcnDiaE4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lunes", "Martes", "Miércoles", "Jueves", "Viernes" }));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Hora inicial:");

        cmbSlcnHoraInED4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "7:00 A.M", "8:00 A.M", "9:00 A.M", "10:00 A.M", "11:00 A.M", "12:00 A.M", "1:00 P.M", "2:00 P.M", "3:00 P.M", "4:00 P.M", "5:00 P.M", "6:00 P.M", "7:00 P.M", "8:00 P.M" }));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Hora final:");

        cmbSlcnHoraFiED4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "7:00 A.M", "8:00 A.M", "9:00 A.M", "10:00 A.M", "11:00 A.M", "12:00 A.M", "1:00 P.M", "2:00 P.M", "3:00 P.M", "4:00 P.M", "5:00 P.M", "6:00 P.M", "7:00 P.M", "8:00 P.M" }));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel9Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(cmbSlcnHoraInED4, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(cmbSlcnHoraFiED4, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel9Layout.createSequentialGroup()
                        .addComponent(rdioHoraE1D4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbSlcnDiaE4, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(rdioHoraE2D4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rdioHoraE3D4)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(jLabel22)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel24)
                .addGap(33, 33, 33))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdioHoraE1D4)
                    .addComponent(rdioHoraE2D4)
                    .addComponent(rdioHoraE3D4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmbSlcnDiaE4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbSlcnHoraInED4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbSlcnHoraFiED4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel10.setBackground(new java.awt.Color(102, 102, 102));
        jPanel10.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Bloques de hora (Día 5):");

        rdioHoraE1D5.setBackground(new java.awt.Color(102, 102, 102));
        rdioHoraE1D5.setForeground(new java.awt.Color(255, 255, 255));
        rdioHoraE1D5.setText("Una hora");

        rdioHoraE2D5.setBackground(new java.awt.Color(102, 102, 102));
        rdioHoraE2D5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rdioHoraE2D5.setForeground(new java.awt.Color(255, 255, 255));
        rdioHoraE2D5.setText("Dos horas");

        rdioHoraE3D5.setBackground(new java.awt.Color(102, 102, 102));
        rdioHoraE3D5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rdioHoraE3D5.setForeground(new java.awt.Color(255, 255, 255));
        rdioHoraE3D5.setText("Tres horas");

        cmbSlcnDiaE5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lunes", "Martes", "Miércoles", "Jueves", "Viernes" }));

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Hora inicial:");

        cmbSlcnHoraInED5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "7:00 A.M", "8:00 A.M", "9:00 A.M", "10:00 A.M", "11:00 A.M", "12:00 A.M", "1:00 P.M", "2:00 P.M", "3:00 P.M", "4:00 P.M", "5:00 P.M", "6:00 P.M", "7:00 P.M", "8:00 P.M" }));

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Hora final:");

        cmbSlcnHoraFiED5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "7:00 A.M", "8:00 A.M", "9:00 A.M", "10:00 A.M", "11:00 A.M", "12:00 A.M", "1:00 P.M", "2:00 P.M", "3:00 P.M", "4:00 P.M", "5:00 P.M", "6:00 P.M", "7:00 P.M", "8:00 P.M" }));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel10Layout.createSequentialGroup()
                        .addComponent(rdioHoraE1D5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbSlcnDiaE5, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addComponent(rdioHoraE2D5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rdioHoraE3D5))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel10Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addComponent(jLabel26)
                                .addGap(80, 80, 80)
                                .addComponent(jLabel27)
                                .addGap(13, 13, 13))
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addComponent(cmbSlcnHoraInED5, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(cmbSlcnHoraFiED5, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(jLabel25)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdioHoraE1D5)
                    .addComponent(rdioHoraE2D5)
                    .addComponent(rdioHoraE3D5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmbSlcnDiaE5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel27)
                    .addComponent(jLabel26))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbSlcnHoraInED5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbSlcnHoraFiED5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Numero de actividad ");

        txtNroActividad.setToolTipText("");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(147, 147, 147))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(19, 19, 19)
                                .addComponent(rdioDiaE1)
                                .addGap(18, 18, 18)
                                .addComponent(rdioDiaE2)
                                .addGap(20, 20, 20)
                                .addComponent(rdioDiaE3)
                                .addGap(16, 16, 16)
                                .addComponent(rdioDiaE4)
                                .addGap(18, 18, 18)
                                .addComponent(rdioDiaE5))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel28))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNroActividad, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtAExtra, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(txtNroActividad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAExtra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(rdioDiaE1)
                    .addComponent(rdioDiaE2)
                    .addComponent(rdioDiaE3)
                    .addComponent(rdioDiaE4)
                    .addComponent(rdioDiaE5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(102, 102, 102));
        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel5.setForeground(new java.awt.Color(102, 102, 102));

        tablaAExtra.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        tablaAExtra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Numero de Actividad", "Actividad Extracurricular"
            }
        ));
        tablaAExtra.setSelectionBackground(new java.awt.Color(204, 204, 204));
        jScrollPane1.setViewportView(tablaAExtra);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(277, 277, 277))
        );

        btnModificarE.setBackground(new java.awt.Color(153, 153, 153));
        btnModificarE.setText("Modificar");
        btnModificarE.setColorHover(new java.awt.Color(204, 204, 255));
        btnModificarE.setColorNormal(new java.awt.Color(153, 153, 153));
        btnModificarE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarEActionPerformed(evt);
            }
        });

        btnEliminarE.setBackground(new java.awt.Color(153, 153, 153));
        btnEliminarE.setText("Eliminar");
        btnEliminarE.setColorHover(new java.awt.Color(204, 204, 255));
        btnEliminarE.setColorNormal(new java.awt.Color(153, 153, 153));
        btnEliminarE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarEActionPerformed(evt);
            }
        });

        btnAgregarE.setBackground(new java.awt.Color(153, 153, 153));
        btnAgregarE.setText("Agregar");
        btnAgregarE.setColorHover(new java.awt.Color(204, 204, 255));
        btnAgregarE.setColorNormal(new java.awt.Color(153, 153, 153));
        btnAgregarE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarEActionPerformed(evt);
            }
        });

        btnAModificacionE.setBackground(new java.awt.Color(153, 153, 153));
        btnAModificacionE.setText("Agregar Modificacion");
        btnAModificacionE.setColorHover(new java.awt.Color(204, 204, 255));
        btnAModificacionE.setColorNormal(new java.awt.Color(153, 153, 153));
        btnAModificacionE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAModificacionEActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnAgregarE, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnModificarE, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(btnEliminarE, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(114, 114, 114)
                                .addComponent(btnAModificacionE, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(209, 209, 209))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnModificarE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEliminarE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAgregarE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnAModificacionE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(223, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1264, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void rdioDiaE1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdioDiaE1ActionPerformed
        // TODO add your handling code here:
       control.habilitarDiasE1();
    }//GEN-LAST:event_rdioDiaE1ActionPerformed

    private void rdioDiaE2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdioDiaE2ActionPerformed
        // TODO add your handling code here:
       control.habilitarDiasE2();
    }//GEN-LAST:event_rdioDiaE2ActionPerformed

    private void rdioDiaE3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdioDiaE3ActionPerformed
        // TODO add your handling code here:
       control.habilitarDiasE3();
    }//GEN-LAST:event_rdioDiaE3ActionPerformed

    private void rdioDiaE4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdioDiaE4ActionPerformed
        // TODO add your handling code here:
        control.habilitarDiasE4();
    }//GEN-LAST:event_rdioDiaE4ActionPerformed

    private void rdioDiaE5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdioDiaE5ActionPerformed
        // TODO add your handling code here:
       if (control.validarVacio(txtAExtra,"Indique el Nombre de la Actividad") == 1 && control.validarVacio(txtNroActividad,"Debe indicar Numero de la actividad")==1 && control.validarNumero(txtNroActividad.getText(),"Debe ingresar un Numero")==1){
        control.habilitarDiasE5();
       } 
    }//GEN-LAST:event_rdioDiaE5ActionPerformed

    private void btnModificarEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarEActionPerformed
        // TODO add your handling code here:
          if (control.validarVacio(txtNroActividad, "Debe indicar el Numero de la Actividad que desea modificar")==1)
        { 
            Actividad act = XMLAE.buscarActividad(Integer.parseInt(txtNroActividad.getText()));
                if (act == null) {
                    JOptionPane.showMessageDialog(null, "La Actividad no Existe", "Error Actividad no encontrada", JOptionPane.ERROR_MESSAGE);
                } else {
                    control.traerDatos(act,txtAExtra,cmbSlcnDiaE1,cmbSlcnDiaE2,cmbSlcnDiaE3,cmbSlcnDiaE4,cmbSlcnDiaE5,cmbSlcnHoraFiED1,cmbSlcnHoraFiED2,cmbSlcnHoraFiED3,cmbSlcnHoraFiED4,cmbSlcnHoraFiED5,cmbSlcnHoraInED1,cmbSlcnHoraInED2,cmbSlcnHoraInED3,cmbSlcnHoraInED4,cmbSlcnHoraInED5);
                    control.desbotones(false, btnAgregarE,btnEliminarE, btnModificarE,btnAModificacionE,txtNroActividad);
                }
        }  
    }//GEN-LAST:event_btnModificarEActionPerformed

    private void btnEliminarEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarEActionPerformed
        // TODO add your handling code here:
   if  (control.validarVacio(txtNroActividad, "Debe indicar el Numero de la Actividad que desea eliminar")==1 && control.validarNumero(txtNroActividad.getText(), "Debe ingresar un Numero")==1 && control.validarNumero(txtNroActividad.getText(), "Debe introducir un numero no letras, ni palabras.")==1 )
           {   
                   Actividad act = XMLAE.buscarActividad(Integer.parseInt(txtNroActividad.getText()));
                    if (act == null) {
                        JOptionPane.showMessageDialog(null, "La Actividad no existe", "Error la Actividad no fue encontrada", JOptionPane.ERROR_MESSAGE);
                    }
                    else
                    {
                         control.traerDatos(act,txtAExtra,cmbSlcnDiaE1,cmbSlcnDiaE2,cmbSlcnDiaE3,cmbSlcnDiaE4,cmbSlcnDiaE5,cmbSlcnHoraFiED1,cmbSlcnHoraFiED2,cmbSlcnHoraFiED3,cmbSlcnHoraFiED4,cmbSlcnHoraFiED5,cmbSlcnHoraInED1,cmbSlcnHoraInED2,cmbSlcnHoraInED3,cmbSlcnHoraInED4,cmbSlcnHoraInED5);
                         int confirmacion = JOptionPane.showOptionDialog(null, "¿Desea Realizar La Operación?", "Confirmación", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, null, null);
                         if (confirmacion == 0){
                            XMLAE.borrarActividad(Integer.parseInt(txtNroActividad.getText()));
                         }
                    control.limpiar(txtAExtra,txtNroActividad);
                    JOptionPane.showMessageDialog(null,"Se ha Eliminado exitosamente la Actividad");
                   }
           }
    }//GEN-LAST:event_btnEliminarEActionPerformed

    private void btnAgregarEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarEActionPerformed
        // TODO add your handling code here:
        if (control.validarVacio(txtAExtra,"Indique el Nombre de la Actividad") == 1 && control.validarVacio(txtNroActividad,"Debe indicar Numero de la actividad")==1 && control.validarGrupo(rdioDiaE1,rdioDiaE2,rdioDiaE3,rdioDiaE4,rdioDiaE5,"Debe ingresar el numero de dias que va realizar la actividad")==1 && control.validarNumero(txtNroActividad.getText(), "Debe introducir un numero no letras, ni palabras.")==1) {
           control.agregarActividadE(actividad, txtAExtra, txtNroActividad, cmbSlcnDiaE1, cmbSlcnDiaE2, cmbSlcnDiaE3, cmbSlcnDiaE4, cmbSlcnDiaE5, cmbSlcnHoraInED1, cmbSlcnHoraFiED1, cmbSlcnHoraInED2, cmbSlcnHoraFiED2, cmbSlcnHoraInED3, cmbSlcnHoraFiED3, cmbSlcnHoraInED4, cmbSlcnHoraFiED4, cmbSlcnHoraInED5, cmbSlcnHoraFiED5, rdioDiaE1, rdioDiaE2, rdioDiaE3, rdioDiaE4, rdioDiaE5);
           JOptionPane.showMessageDialog(null,"Se ha Agregado Exitosamente la Actividad");     
        }      
        
    }//GEN-LAST:event_btnAgregarEActionPerformed

    private void btnAModificacionEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAModificacionEActionPerformed
        // TODO add your handling code here:
        if (control.validarGrupo(rdioDiaE1,rdioDiaE2,rdioDiaE3,rdioDiaE4,rdioDiaE5,"Debe ingresar el numero de dias que va realizar la actividad")==1) {
               control.agregarModificacion(XMLAE, txtAExtra, txtNroActividad,cmbSlcnDiaE1, cmbSlcnDiaE2, cmbSlcnDiaE3, cmbSlcnDiaE4, cmbSlcnDiaE5, cmbSlcnHoraFiED1, cmbSlcnHoraFiED2,cmbSlcnHoraFiED3,cmbSlcnHoraFiED4,cmbSlcnHoraFiED5,cmbSlcnHoraInED1,cmbSlcnHoraInED2,cmbSlcnHoraInED3,cmbSlcnHoraInED4,cmbSlcnHoraInED5,rdioDiaE1,rdioDiaE2,rdioDiaE3,rdioDiaE4,rdioDiaE5);
               control.desbotones(true, btnAgregarE,btnEliminarE,btnModificarE,btnAModificacionE,txtNroActividad);
               control.limpiar(txtAExtra,txtNroActividad);  
               JOptionPane.showMessageDialog(null,"Se ha Modificado Exitosamente la Actividad");
        }
    }//GEN-LAST:event_btnAModificacionEActionPerformed

      private void llenarTablaAE(controlXMLAE datosXMLAE){
        String[] columna = {"Numero de Actividad","Actividad Extracurricular"};
        DefaultTableModel dtm2 = new DefaultTableModel(null, columna);
        ArrayList<Actividad> datosA = datosXMLAE.listaAExtraxml();
        for(Actividad A : datosA){
                String[] row = {Integer.toString(A.getNroActividadE()),A.getNombreAExtra()};
                dtm2.addRow(row);
        }
        tablaAExtra.setModel(dtm2);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rsbuttom.RSButtonMetro btnAModificacionE;
    private rsbuttom.RSButtonMetro btnAgregarE;
    private rsbuttom.RSButtonMetro btnEliminarE;
    private rsbuttom.RSButtonMetro btnModificarE;
    private javax.swing.JComboBox<String> cmbSlcnDiaE1;
    private javax.swing.JComboBox<String> cmbSlcnDiaE2;
    private javax.swing.JComboBox<String> cmbSlcnDiaE3;
    private javax.swing.JComboBox<String> cmbSlcnDiaE4;
    private javax.swing.JComboBox<String> cmbSlcnDiaE5;
    private javax.swing.JComboBox<String> cmbSlcnHoraFiED1;
    private javax.swing.JComboBox<String> cmbSlcnHoraFiED2;
    private javax.swing.JComboBox<String> cmbSlcnHoraFiED3;
    private javax.swing.JComboBox<String> cmbSlcnHoraFiED4;
    private javax.swing.JComboBox<String> cmbSlcnHoraFiED5;
    private javax.swing.JComboBox<String> cmbSlcnHoraInED1;
    private javax.swing.JComboBox<String> cmbSlcnHoraInED2;
    private javax.swing.JComboBox<String> cmbSlcnHoraInED3;
    private javax.swing.JComboBox<String> cmbSlcnHoraInED4;
    private javax.swing.JComboBox<String> cmbSlcnHoraInED5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rdioDiaE1;
    private javax.swing.JRadioButton rdioDiaE2;
    private javax.swing.JRadioButton rdioDiaE3;
    private javax.swing.JRadioButton rdioDiaE4;
    private javax.swing.JRadioButton rdioDiaE5;
    private javax.swing.ButtonGroup rdioGroupDiaE;
    private javax.swing.ButtonGroup rdioGroupDiaE1;
    private javax.swing.ButtonGroup rdioGroupDiaE2;
    private javax.swing.ButtonGroup rdioGroupDiaE3;
    private javax.swing.ButtonGroup rdioGroupDiaE4;
    private javax.swing.ButtonGroup rdioGroupDiaE5;
    private javax.swing.JRadioButton rdioHoraE1D1;
    private javax.swing.JRadioButton rdioHoraE1D2;
    private javax.swing.JRadioButton rdioHoraE1D3;
    private javax.swing.JRadioButton rdioHoraE1D4;
    private javax.swing.JRadioButton rdioHoraE1D5;
    private javax.swing.JRadioButton rdioHoraE2D1;
    private javax.swing.JRadioButton rdioHoraE2D2;
    private javax.swing.JRadioButton rdioHoraE2D3;
    private javax.swing.JRadioButton rdioHoraE2D4;
    private javax.swing.JRadioButton rdioHoraE2D5;
    private javax.swing.JRadioButton rdioHoraE3D1;
    private javax.swing.JRadioButton rdioHoraE3D2;
    private javax.swing.JRadioButton rdioHoraE3D3;
    private javax.swing.JRadioButton rdioHoraE3D4;
    private javax.swing.JRadioButton rdioHoraE3D5;
    private javax.swing.JTable tablaAExtra;
    private javax.swing.JTextField txtAExtra;
    private javax.swing.JTextField txtNroActividad;
    // End of variables declaration//GEN-END:variables
}
